### ISSUE TITLE
App styling foundation

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/wikonnect#14]
As a frontend engineer, I would like a style foundation to work with

- [ ] Decide on a framework like Bootstrap/Bulma etc. if needed
- [ ] Implement general styles for elements like headings, links, buttons, forms etc from designs.
- [ ] Add the header and logo
- [ ] Add the footer

**Comment by mosesokemwa** [comment]
@proverbial-ninja could you confirm if this was done or if it needs an update
