### ISSUE TITLE
[FEATURE] [FRONTEND] Dashboard design and creation for M&E data visualisation

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#216]
### Describe the user story:

As Wikonnect we would like to monitor the collective impact  made through the platform
This requires tracking of specific data points as documented by the M&E team.
The collection can be done by a mix of online surveys and pre-collected data(e.g. completion rate of courses, most taken lesson...)

Further details can be found [here](https://docs.google.com/spreadsheets/d/0B58FLSwyzdApUzRpMUFicFdlSHByazZEWTY3MDFWUVo2amlz/edit#gid=1595611418) - access requests might be required

The data received is structured to fit [ember-charts](https://opensource.addepar.com/ember-charts/#/vertical-bar) data models.

**Comment by brianmarete** [comment]
We've shifted to using Asha for data visualization and tracking of M&E data
