### ISSUE TITLE
[FEATURE] [BACKEND] Public User API

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#255]
### Describe the bug:

Logged out user should be able to get public user information on public profile 

### Expected Behavior

API /user/slug should have some publicly available info ... 

### Current Behavior

requires auth to get user

**Comment by mosesokemwa** [comment]
@proverbial-ninja I will have to set some privacy settings on the profile, depending on the users preference.
If I choose to have my profile seen publicly, I can check a box[true:false] and that will sort the issue for now.

If we need to give the user powers to select what info should be public or not, we will extend the above functionality
