### ISSUE TITLE
[FEATURE] [BACKEND] Validate token endpoint

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#256]
### Describe the user story:

3rg party should be able to validate auth token

**Comment by mosesokemwa** [comment]
@proverbial-ninja 
1. What do you mean by 3rd party? What auth process are you using?
2. The backend validates token the same way it does with the frontend we have, so it should a matter of replicating the same process


IMO this should not be a feature request as it already does what it's supposed to do
