### ISSUE TITLE
[BUG] h5p interactive video not going into fullscreen correctly

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#260]
### Describe the bug:

User can't go into fullscreen mode in h5p interactive video eg.
https://app.wikonnect.org/chapter/chapter2

### Expected Behavior

fullscreen should cover 100% of screen

### Current Behavior

fullscreen only takes *approx 150px

**Comment by proverbial-ninja** [comment]
@Jakeii would you mind taking a look

**Comment by Jakeii** [comment]
@proverbial-ninja Weird! no problem, I'll have a look

**Comment by Jakeii** [comment]
@proverbial-ninja It's because the css from h5p-standalone wasn't added (by me). It's included in the H5P iframe but not to the top level.

You can import it in `ember-cli-build.js`
```javascript
  app.import('node_modules/h5p-standalone/dist/styles/h5p.css');
```
