### ISSUE TITLE
[BUG] saving h5p chapter shouldn't require lesson ID

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#267]
### Tell us about your browser and operating system:
- Operating System:
- NodeJS Version:
- Ember Version:

### Screenshots where applicable

**Comment by proverbial-ninja** [comment]
This error is back.
occurs when i try to update chapters "approved" status

**Comment by mosesokemwa** [comment]
> This error is back.
> occurs when I try to update chapters "approved" 

@proverbial-ninja 
What's the exact error message you are getting?
Provide a screenshot where possible
