### ISSUE TITLE
[BUG] db:reset during tests failing 

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#285]
### Describe the bug:

getting this error in my tests "I'm guessing it's a migration issue"

```
cy.task('db:reset') failed with the following error:

> alter table "users" drop column "private" - column "private" of relation "users" does not exist

Because this error occurred during a before each hook we are skipping all of the remaining tests.
```

### Tell us about your browser and operating system:
- Operating System:
- NodeJS Version:
- Ember Version:

### Screenshots where applicable

**Comment by mosesokemwa** [comment]
@proverbial-ninja you are a little light on the details, there isnt much I can do with the provided info. Also we are trying to enforce the guidelines set.

**Comment by proverbial-ninja** [comment]
I'm not sure what else to add ?
