### ISSUE TITLE
[BUG] User object should also return users roles

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#308]
### Describe the bug:

User object returns empty user roles array

**Comment by mosesokemwa** [comment]
User object returns empty user roles array because they have no been assigned any role yet

**Comment by mosesokemwa** [comment]
It does return user roles.
check the userRoles object

check the docs [here](https://tunapanda.github.io/wikonnect/#api-Authentication-GetAUser)
