### ISSUE TITLE
Component Library  / Design System

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#31]
As a front-end developer, I would like to have a standard set of UI components to have a uniform look and feel.

- [ ] Buttons

- [ ] Typography

- [ ] Colors

- [ ] Form Elements

- [ ] Navigation

- [ ] Feedback / Alerts

- [ ] Dialogs/Modals

- [ ] Empty States

- [ ] Cards

- [ ] Lists / SubLists

- [ ] Tabs

- [ ] Tables

- [ ] Icons

- [ ] Documentation

**Comment by Jakeii** [comment]
Will probably need an upload button UI element
