### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/wikonnect#32]
As a developer, I would like a dockerize application for streamlined deployments.

- [ ] Docker containers for: frontend/static/nginx, API, database, elasticsearch, redis(?)
- [ ] Docker compose to get it all working
- [ ] Research Kubernetes

**Comment by BonfaceKilz** [comment]
@Jakeii for now is it ok to just dockerize things in one container? I'd suggest maybe to do the ops work in a separate repo and tracking things there? Does that make sense?

My motivation for dockerizing things is that Cypress doesn't work in FreeBSD(which is really sad)[0]

[0] https://github.com/cypress-io/cypress/issues/3382
