### ISSUE TITLE
[FEATURE] [BACKEND] Oembed Provider Response

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#500]
### Describe the user story:
oEmbed is a format for allowing an embedded representation of a URL on third party sites. The simple API allows a website to display embedded content (such as photos or videos) when a user posts a link to that resource, without having to parse the resource directly.
Back end should respond to Oembed request with correct respose

### Tasks (where applicable)

- [x]  Meet requirements below

### Requirements
**Oembed Backend**

Create api endpoint like
 ``` http://rootUrl/api/v1/oembed```
 that takes in a url query parameter 
 ``` http://rootUrl/api/v1/oembed?url=http://localhost:4200/chapter/IPUkk_YAA9w```
and outputs this json based on the chapter id in the url

 ```
 {
	"version": "1.0",
	"type": "h5p",
	"provider_name": "Wikonnect",
	"provider_url": "http://app.wikonnect.org/",
	"width": 425,
	"height": 344,
	"title": "Cyber bullying",
	
	"html":
		"<iframe width=\"560\" height=\"315\" src=\"http://localhost:4200/embed/IPUkk_YAA9w\" ></iframe>",
}
```
Remember to also add the callback url to the iframe code if it exists on the url query param.

**Comment by mosesokemwa** [comment]
@proverbial-ninja why have you re-opened this issue?

**Comment by proverbial-ninja** [comment]
> @proverbial-ninja why have you re-opened this issue?
I was till typing the reason when you sent this ... 

There's a bug where when the oembed url has url parmeters the api fails
eg https://app.wikonnect.org/api/v1/oembed?url=https://app.wikonnect.org/chapter/IPUkk_YAA9w?callbackUrl=https://webhook.com

Thought it's better to reopen issue instead of creating another one

**Comment by mosesokemwa** [comment]
This was not in the original description and it looks like a nested query param.

Whats the callback used for?

**Comment by proverbial-ninja** [comment]
> This was not in the original description and it looks like a nested query param.

It is the last line in the original description.

> Whats the callback used for?

Its how the third party lets us know where to send progress information.

**Comment by mosesokemwa** [comment]
@proverbial-ninja can we enforce a callback as a query param for oembed api endpoint as opposed to the having nested query params

```There's a bug where when the oembed url has url parmeters the api fails
eg https://app.wikonnect.org/api/v1/oembed?url=https://app.wikonnect.org/chapter/IPUkk_YAA9w&callbackUrl=https://webhook.com```

**Comment by proverbial-ninja** [comment]
> @proverbial-ninja can we enforce a callback as a query param for oembed api endpoint as opposed to the having nested query params
> 
> ```
> eg https://app.wikonnect.org/api/v1/oembed?url=https://app.wikonnect.org/chapter/IPUkk_YAA9w&callbackUrl=https://webhook.com```
> ```

I agree , as long as the query param is still there in the "html" value of the the oembed api response

**Comment by mosesokemwa** [comment]
I found a way to make it work with internal node libraries, so I guess we are good
