### ISSUE TITLE
[BUG] Publish Failing on KKL instance

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#508]
### Describe the bug:

Getting a {"errors":["Bad Request"]} when publishing on KKL
PUT | http://localhost:4200/api/v1/chapters/{chapter id}

### Expected Behavior

Should return 201, and Should update record in Database

**Comment by mosesokemwa** [comment]
Closing issue because the closing trigger failed to initiate also it's already fixed in #515
