### ISSUE TITLE
[BUG] Google signup & registration failing [WIK-24]

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#552]
### Describe the bug:

Nothing happens when user clicks the Google signup or login button

### Expected Behavior

A google authentication screen should pop uup allowing the user to sign up or login

### Steps to reproduce
Go to https://app.wikonnect.org/signup and click the signup button

### Error Log / Stack Trace (where applicable)
Google auth failed:  Expected configuration value apiKey to be defined for provider named google-oauth2-bearer

**Comment by mosesokemwa** [comment]
@proverbial-ninja for context the conversation is on [jira](https://tunapanda.atlassian.net/browse/WIK-24)
