### ISSUE TITLE
[BUG] Update Wikonnect Classic's landing page

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#561]
### Describe the bug:

We are running an instance of Wikonnect that should have a Wikonnect centric landing page

### Expected Behavior

The landing page should show this [details](https://github.com/tunapanda/wikonnect/blob/master-old/frontend/app/templates/index.hbs) or any other agreed on by the design and/or product team

### Steps to reproduce
Visit [Wikonnect Landing](https://app.wikonnect.org) to see the page

### Error Log / Stack Trace (where applicable)
No stack trace available

### Screenshots where applicable
<img width="489" alt="Screenshot 2021-02-02 at 15 27 28" src="https://user-images.githubusercontent.com/13944912/106712659-54012780-660a-11eb-8b30-9498d676b69e.png">

**Comment by 0xMurage** [comment]
merged with #234
