### ISSUE TITLE
[BUG] Integration tests failing due to a bug in Cypress on sites that implement SRI

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#569]
### Describe the bug:

Ember main vendor script is blocked on the page visit due to invalid hashes causing the tests loading site pages to fail (https://github.com/cypress-io/cypress/issues/2393)

### Expected Behavior

Ember production builds include integrity hashes on the bundled scripts and styles. Cypress should not tamper with resource hashes during tests.

### Current Behavior
Chrome/Electron/Firefox browsers used in Cypress integration tests fail to load the views and respective content. Ember's main vendor script bundling other scripts dependencies is blocked due to an invalid resource digest.

### Steps to reproduce

1. Setup the server as per the [documentation](https://github.com/tunapanda/wikonnect/blob/master/README.md)
2. Build the frontend Ember application with production flag (`ember build --prod`)
3. Implement a basic step that verifies anything on the page.
4. Run Cypress tests on the root of the project (`yarn cy:run`)
5. Inspect the DevTools console on the browser used to view blocked resources.
 

### Error Log / Stack Trace (where applicable)
```Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/assets/vendor-825ac11742a54243d6fc4946a75bc561.js' with computed SHA-256 integrity 'Y4mWg2Px4n1tVcsbi+aciYMksMh2wLhbJ7qvt/Q3LVE='. The resource has been blocked.```

### Tell us about your browser and operating system:
- Operating System: Linux x64
- NodeJS Version: 12.20.0
- Ember Version: 3.14.0

### Screenshots where applicable

![Screenshot_from_2021-02-04_14-01-51](https://user-images.githubusercontent.com/25152892/106938038-85bfde80-672f-11eb-9e03-466d4e24dd6f.png)

**Comment by brianmarete** [comment]
@mimidotsuser was this issue resolved?

**Comment by 0xMurage** [comment]
"Yes" through a workaround of testing with the development build files.
The [solution provided](https://github.com/cypress-io/cypress/issues/2393#issuecomment-631637551)  by the Cypress team does not work as expected as it crashes the tests and increases page load time significantly (by extra 15 seconds on each page load)

**Comment by brianmarete** [comment]
Thanks for that @mimidotsuser, Closing the issue
