### ISSUE TITLE
[FEATURE] [BACKEND] User cannot upload large H5P content files

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#653]
### Describe the bug:

User cannot upload large H5P content files

### Expected Behavior

User should be able to upload H5P content files that are less than 5MB

### Current Behavior

Error emitted when uploading existing H5P zip file through the editor

### Steps to reproduce
Upload a H5P file through through the editor

### Tell us about your browser and operating system:
- Operating System:
- NodeJS Version:
- Ember Version:

### Screenshots where applicable
![Screenshot from 2021-03-26 10-48-12](https://user-images.githubusercontent.com/25152892/112599307-d34bf400-8e20-11eb-85cc-7aa590609693.png)

**Comment by mosesokemwa** [comment]
Fixed by increasing upload size in nginx
