### ISSUE TITLE
API course/module joining

### ISSUE THREAD

**Issue by mrlarso** [tunapanda/wikonnect#69]
Respond to course/module creation and edit requests by updating the join tables (course_modules, module_lessons).

Closes #62

**Comment by mosesokemwa** [comment]
Checklist
- [x] Joining tables modules files
- [x] DB seeds for joining tables(course_modules, modules_lessons)
- [x] Handle PUT for a course and a module joining tables object
- [x] Record POST for a course and a module joining tables object
- [x] Document code using JSDoc standard
