### ISSUE TITLE
Frontend Authorisation & Authentication

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/wikonnect#7]
As a user, I would like to be able to login to the app.

- [x] Login and registration pages
- [x] Login and registration form components
- [x] Login and registration form validation
- [x] Comunicate with API for Authentication and Authorization using ember-simple-auth & ember-simple-auth-token
- [x] A service to manage and maintain sessions
- [x] Test login and registration form

Depends on #6

**Comment by mrlarso** [comment]
User session does not persist on refresh or route change
