### ISSUE TITLE
[BUG] Project setup issues on macOS running M1 chip

### ISSUE THREAD

**Issue by KingKimani** [tunapanda/wikonnect#702]
### Describe the bug:
I have been having issues setting up the Wikonnect project on my Mac M1 system. The setup process is failing while following either Docker or manual steps. The backend dependencies installation step is failing when installing the Sharp dependency.

### Expected Behavior
Setting up the project on Docker or installing the backend dependencies while following the manual setup steps should not fail on macOS running on M1 chip.

### Steps to reproduce
Related issue https://github.com/lovell/sharp/issues/2460#issue-751087861

### Tell us about your browser and operating system:
- Operating System: macOs 11.0.1
- NodeJS Version: v14.16
- Ember Version: v3.24.0

### Screenshots where applicable
<img width="1440" alt="first" src="https://user-images.githubusercontent.com/53226753/115712230-2ad87380-a37d-11eb-9d81-be5cd41941c5.png">
<img width="1440" alt="second " src="https://user-images.githubusercontent.com/53226753/115712264-3af05300-a37d-11eb-8bf4-596bd33eb7e2.png">

**Comment by mosesokemwa** [comment]
@KingKimani if you managed to solve this, could you describe the process here
