### ISSUE TITLE
new user email confirmation

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#76]
A user should be able to confirm an email using a generated token that is sent to them
- [x] generate email token
- [x] send email template
- [ ] tests

**Comment by 3xorcis7** [comment]
//solved

**Comment by mosesokemwa** [comment]
We are almost getting to solved, just a few things left 
- add missing test(s) for the email verification
- KoaJS encapsulates res and req into ctx which is a single object [read more here](https://github.com/koajs/koa/blob/master/docs/api/context.md)
