### ISSUE TITLE
forgot password notification

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#81]
A user should be able to reset a forgotten password as long as they have a valid
- [ ] email validation route
- [ ] password reset route
- [ ] tests

Closes #80

**Comment by Renice-Owino** [comment]
I am working on this with the help of Zack

**Comment by IjayAbby** [comment]
I would love to contribute on this.

**Comment by Phoebe-oigara** [comment]
``

**Comment by Phoebe-oigara** [comment]
i will try contributing to this

**Comment by Tongjason6** [comment]
Contributing on this

**Comment by nancy-code** [comment]
Contrubuting

**Comment by proverbial-ninja** [comment]
Sorry, this is already in development at the moment
