### ISSUE TITLE
share page component

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#84]
A user I should be able to share a link to social media
- [ ] twitter
- [ ] facebook

**Comment by avicndugu** [comment]
I have created this component. I looked through the designs but I couldn't find a page with how they are expected to be aligned. So the button currently look like this in the component:
![localhost_4200_course_module_lesson_chapter_chapter1](https://user-images.githubusercontent.com/37213663/77249471-417c3a80-6c52-11ea-85fe-a6029d941f91.png)
