### ISSUE TITLE
In platform notification

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#88]
A user should be able to receive a notification based on triggers that are preset
Trigger:
- invited user complete registration
- new course creation
 - new badge awarded

- [ ] set up notification triggers
- [ ] notification table
- [ ] tests

**Comment by Collins-Kareri** [comment]
Working on it @mosesokemwa

**Comment by mosesokemwa** [comment]
@Collins-Kareri once you are done make a pull request against the master branch
